### ISSUE TITLE
"google.apputils.app.Error: <not found>"

### ISSUE THREAD

**Issue by tmst** [google/apis-client-generator#11]
Am trying to generate a Dart client library. Here's my command. I get the same result when entering the URL of the discovery doc rather than --input=myapi.json:

generate_library --api_name= --api_version=v1 --language=dart --output_dir=lib --input=myapi.json

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/googleapis/codegen/generate_library.py", line 230, in <module>
    app.run()
  File "/usr/lib/python2.7/site-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/lib/python2.7/site-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/lib/python2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/usr/lib/python2.7/site-packages/googleapis/codegen/generate_library.py", line 137, in main
    content = GetApiDiscovery(FLAGS.api_name, FLAGS.api_version)
  File "/usr/lib/python2.7/site-packages/googleapis/codegen/generate_library.py", line 225, in GetApiDiscovery
    raise app.Error(error)
google.apputils.app.Error: {u'code': 404, u'message': u'Not Found', u'errors': [{u'domain': u'global', u'message': u'Not Found', u'reason': u'notFound'}]}
[/home/tom/work/dart/dart-sdk/discovery_api_dart_client_generator/bin] > dart --version 
Dart VM version: 1.8.5 (Tue Jan 13 12:39:16 2015) on "linux_ia32"

**Comment by tmst** [comment]
Note: The command *did* include the api_name: "myapi".

**Comment by aiuto** [comment]
Do not include --api_name and --api_version. Just use --input=myapi.json.  It picks up the api name and version from the discovery file.

**Comment by tmst** [comment]
When I don't include --api_name and --api_version, errors are reported that 
they are absent:

super(DartApi, self).__init__(discovery_doc)
  File "/usr/lib/python2.7/site-packages/googleapis/codegen/api.py", line 103, 
in __init__
    wire_name=discovery_doc['name'])
KeyError: 'name'

When I include "name" and "version" at the top level of the discovery document 
(and run without --api_name and --api_version), the script completes without 
error but doesn't output anything into the specified directory.

**Comment by aiuto** [comment]
How did you get that discovery file, from the Google cloud tools or hand built?
If from the google tools, that might be a problem in the discovery generator for Cloud Endpoints. If you hand built it, then you should include name and id.   Take a look at some examples (e.g.
https://www.googleapis.com/discovery/v1/apis/discovery/v1/rest)

You need, almost everything up to parameters. Add ownerDomain and ownerName so the libraries come out namespaced correctly for your use.

**Comment by tmst** [comment]
It's the discovery doc generated in Google cloud tools and published at appspot.com.

The example above is very much longer than the one published for my API, which is only 36 lines!

I'm now getting the following:
NoSuchMethodError: method not found: 'toLowerCase'

**Comment by aiuto** [comment]
I can not reproduce with the current source. Is your copy stale? Can you attache a sanitized copy of the discovery?

**Comment by tmst** [comment]
I can't tell what version of this package I'm using but it was cloned 2 days ago. Here's a copy of the sanitized discovery document:

{
 "kind": "discovery#directoryList",
 "discoveryVersion": "v1",
 "items": [
  {
   "kind": "discovery#directoryItem",
   "id": "discovery:v1",
   "name": "discovery",
   "version": "v1",
   "title": "APIs Discovery Service",
   "description": "Lets you discover information about other Google APIs, such as what APIs are available, the resource and method details for each API.",
   "discoveryRestUrl": "https://<myapi>.appspot.com/_ah/api/discovery/v1/apis/discovery/v1/rest",
   "discoveryLink": "./apis/discovery/v1/rest",
   "icons": {
    "x16": "http://www.google.com/images/icons/feature/filing_cabinet_search-g16.png",
    "x32": "http://www.google.com/images/icons/feature/filing_cabinet_search-g32.png"
   },
   "documentationLink": "https://developers.google.com/discovery/",
   "preferred": true
  },
  {
   "kind": "discovery#directoryItem",
   "id": "MyAPI:v1",
   "name": "MyAPI",
   "version": "v1",
   "description": "Ferris-based MyAPI API",
   "discoveryRestUrl": "https://<myapi>.appspot.com/_ah/api/discovery/v1/apis/MyAPI/v1/rest",
   "discoveryLink": "./apis/MyAPI/v1/rest",
   "icons": {
    "x16": "http://www.google.com/images/icons/product/search-16.gif",
    "x32": "http://www.google.com/images/icons/product/search-32.gif"
   },
   "preferred": true
  }
 ]
}

**Comment by tmst** [comment]
I just fired up the development server and discovered that there are (at least) two versions of the discovery document for a given API - one published on localhost and the other at the appspot.com domain. The one on localhost is much longer and more complete.
