### ISSUE TITLE
Document Django <=1.8 requirement

### ISSUE THREAD

**Issue by mmdriley** [google/apis-client-generator#16]
As documented in #13, apis-client-generator does not work with Django 1.8 and requires Django 1.7.

The [README says](https://github.com/google/apis-client-generator/blob/7c3e92779e691233a5d9c78f057fbe0d6587875c/README#L46) Django "version 1.8 or above is required", which is opposite of true.

**Comment by aiuto** [comment]
I am using it with Django 1.8. What problem do you see.

**Comment by aiuto** [comment]
This may be an ordering problem. We migrated to 1.8 on 7/6/15, which was a week after the original bug. So the comment about needed 1.7 is obsolete. Probably can't use 1.9, but I have not tried.

**Comment by mcohoon** [comment]
I tested 1.8 and it seems to be okay, I updated the pull request to reflect this.

**Comment by mmdriley** [comment]
Hm, my bad. Checked and 1.8 works for me as well.

Perhaps I was actually using 1.9 before, by mistake? Seems like that's the case for #13 as well.

The reason for 1.9 incompatibility: https://docs.djangoproject.com/en/1.9/releases/1.9/#django-template-base-add-to-builtins-is-removed

**Comment by aiuto** [comment]
My plan is to let someone cope with it when we deprecate 1.8. If Ethan
can't figure it out, I'll do it. FWIW, we are not set up to accept
contributions at all from github. We don't have a CONTRIBUTING file which
instructs people to sign the CLA. It's only when I am actively avoiding
real work I ever answer something on github​

**Comment by aiuto** [comment]
done in b584f769838e4d97da38475543b523787886ec32
