### ISSUE TITLE
C++: implementations of some functions are not generated.

### ISSUE THREAD

**Issue by Stvad** [google/apis-client-generator#19]
I've been trying to use youtube API wrapper generated by this generator when I've encountered the following problem -  for some functions generator is not generating implementations - only declarations and documentation.
You can see this on an example of already generated API provided here (https://github.com/google/google-api-cpp-client/tree/master/service_apis/youtube/google/youtube_api ) 
So for example for these functions in live_broadcast.h/cc:
get_snippet
mutable_snippet
get_content_details
mutable_contentDetails
etc.
There is only declarations generated.
 I'm getting similar results by running generator myself.

Workaround that I'm using right know is to use option:
--monolithic_source_name
In this case - implementations are generated the way they should be.

**Comment by SurferJeffAtGoogle** [comment]
Fixed.
