### ISSUE TITLE
PSR compliance PHP client generator

### ISSUE THREAD

**Issue by DaanBiesterbos** [google/apis-client-generator#23]
Hi guys, 

Although I really like the possibilities of this library I must admit that the generated source code is severely outdated.  At least for the PHP part. Are there plans to start using namespaces and generate code that complies to the PSR coding guidelines? I don't mind to contribute. 

Kind regards,
Daan

**Comment by aiuto** [comment]
Current work in generic libraries for Google services is here: http://www.grpc.io/.  That is the place where you should be looking for enhancements.

**Comment by DaanBiesterbos** [comment]
Love the framework. Thank you for pointing it out. I work with protobuf in Java. But how is protobuf under PHP? Is is stable / performant enough for production?
