### ISSUE TITLE
Recommended way for generating clients?

### ISSUE THREAD

**Issue by bootstraponline** [google/apis-client-generator#31]
What's the recommended way for generating clients from API discovery descriptions? It looks like this library is no longer actively developed.

**Comment by tswast** [comment]
Yes, it is still the recommended way for API discovery descriptions.

For gRPC APIs you can use the native gRPC generation from proto files or https://github.com/googleapis/toolkit

**Comment by bootstraponline** [comment]
Thanks. It looks like a bunch of commits just landed. 😄
