### ISSUE TITLE
Last release to PIP was 2013-08-20. Make new release

### ISSUE THREAD

**Issue by bootstraponline** [google/apis-client-generator#32]
apis-client-generator crashes on `testing_v1.json` due to None descriptions on enums. It looks like master already has a fix for this issue. It'd be nice to make a new release to PIP.

**Comment by bootstraponline** [comment]
https://pypi.python.org/pypi/google-apis-client-generator says the last release was 2013-08-20

**Comment by tswast** [comment]
Done. I have just released version 1.4.3 at https://pypi.python.org/pypi/google-apis-client-generator/1.4.3

**Comment by tswast** [comment]
@aiuto I believe we can close this issue. (I don't have write access so cannot myself)

**Comment by bootstraponline** [comment]
Thanks!
