### ISSUE TITLE
Broken code generated using master on Java target

### ISSUE THREAD

**Issue by bootstraponline** [google/apis-client-generator#34]
```
generate_library \
    --input=./testing_v1.json \
    --language=java \
    --output_dir=./testing/src/main/java
```

- [testing_v1.json](https://github.com/TestArmada/flank/blob/master/cloud_testing/apis/testing_v1.json)

Results in:

```
./gradle/gradlew -p cloud_testing/cloud_api_poc clean build

> Task :testing:compileJava
/flank/cloud_testing/apis/testing/src/main/java/com/google/testing/Testing.java:918: error: method does not override or implement a method from a supertype
    @Override
    ^
/flank/cloud_testing/apis/testing/src/main/java/com/google/testing/Testing.java:920: error: cannot find symbol
      return (Builder) super.setBatchPath(batchPath);
                            ^
  symbol: method setBatchPath(String)
2 errors


FAILURE: Build failed with an exception.
```

**Comment by bootstraponline** [comment]
>google-api-client-1.22.0.jar!/com/google/api/client/googleapis/services/json/AbstractGoogleJsonClient.class

has no method `setBatchPath(batchPath);`

**Comment by crlsndrsjmnz** [comment]
I have the same issue when creating a new "Google Cloud Module" in Android Studio:

```
Error:(279, 5) error: method does not override or implement a method from a supertype
Error:(281, 29) error: cannot find symbol method setBatchPath(String)
```

I don't see anybody else having this problem and it looks to me that I need `google-api-client-1.23.0`, how can I solve this?

This is my `build.gradle` for the `backend` module:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.appengine:gradle-appengine-plugin:1.9.56'
    }
}

repositories {
    jcenter();
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'appengine'

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

dependencies {
    appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.56'
    compile 'com.google.appengine:appengine-endpoints:1.9.56'
    compile 'com.google.appengine:appengine-endpoints-deps:1.9.56'
    compile 'javax.servlet:servlet-api:2.5'
}

appengine {
    downloadSdk = true
    appcfg {
        oauth2 = true
    }
    endpoints {
        getClientLibsOnBuild = true
        getDiscoveryDocsOnBuild = true
    }
}
```

**Comment by janjsimon** [comment]
I had the same problem recently. Try to set:

```
appengine {
    // ...
    endpoints {
        googleClientVersion = '1.23.0'
        // ...
    }
}
```

and use the same version in other google api client dependencies too, e.g.:

`compile 'com.google.api-client:google-api-client:1.23.0'`

You can use the following command to review the version of your module's dependencies:

`./gradlew backend:dependencies`

**Comment by FlyingRam** [comment]
All of the sudden I am getting this error...was compiling this morning.  The only change I made was to my endpoint API.

**Comment by jlmalone** [comment]
Basically a mass force upgrade to 1.23 because of breaking change. I agree that it is strange that code which compiled before stopped compiling which is what happened to me too.

**Comment by isdsava** [comment]
Thank you very much janjsimon this worked a treat.

**Comment by aiuto** [comment]
It looks like this is a problem with google-api-java-client.  Not much to do here.
